### PR TITLE
Feature/change bottom nav to css and layouts

### PR DESCRIPTION
**Pull request by marco-villanueva**
This PR enables BottomNav's vertical navigation and allows you to enable the default NextJS configuration inside the Pages folder.

### CODE REVIEW

**Comment by OOCAZ** [comment]
Hey Marco, I see thw rest is still failing, would it be best to remove the app directory all together to make this PR work?

**Comment by OOCAZ** [comment]
merged

**Comment by marco-villanueva** [comment]
It already pass... sorry, I didn't import global css on the right file. but it's already fixed

**Comment by OOCAZ** [comment]
all good! thanks for the contribution! It looks so good on mobile!!!! Awesome work man, changes are live on: https://honeybeeobt.org/workflow/

**Pull request merged**
